- name: setup backend configuration file
  hosts: backend
  become: true
  tasks:
  - name: disable nodejs default version
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable nodejs-20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: installed
  - name: expense useradd 
    ansible.builtin.user:
      name: expense

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  - name: unarchive backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes
