- name: configuration of db file
  hosts: db
  become: true
  tasks:
  - name: install mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: mysql service enable and start
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: install mysql python dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
  # check root password set up or not
  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: db.kanakam.top
      filter: version
    register: mysql_root_output
    ignore_errors: yes
  - name: print the db output
    ansible.builtin.debug:
      msg: "my sql root password output is: {{mysql_root_output}}"