- name: db configuration
  hosts: db
  become: true
  vars:
    login_host: db.kanakam.top
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
  - name: enable and start the mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: install mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9
  #check root password setup or not
  - name: check db connections
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{ login_host }}" #db ip
      filter: version
    ignore_errors: yes 
    register: mysql_output
  - name: print the output
    ansible.builtin.debug:
      msg: "{{mysql_output}}"






  # - name: setup root password
  #   ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"