- name: db configuration
  hosts: db
  become: true
  vars:
    login_host: 172.31.20.146
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
  - name: enable and start the mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  #check root password setup or not
  - name: check db connections
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{ login_host | int }}" #db ip
      filter: version
      ignore_errors: yes 
    register: mysql_output







  # - name: setup root password
  #   ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"