- name: configuration of frontend file
  hosts: frontend
  become: true
  hosts:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start and enabled nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  # - name: remove default web file
  #   ansible.builtin.file:
  #     path: /usr/share/nginx/html
  #     state: absent