- name: frontend configuration file
  hosts: frontend
  become: true
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: remove default web content
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  - name: unarchive and download the fntend code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  - name: copy frontend code
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
